version: '3'

services:
  h-ui:
    image: jonssonyan/h-ui
    container_name: h-ui
    restart: always
    network_mode: host
    volumes:
      - /h-ui/bin:/h-ui/bin
      - /h-ui/data:/h-ui/data
      - /h-ui/export:/h-ui/export
      - /h-ui/logs:/h-ui/logs
    environment:
      TZ: Asia/Shanghai